services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    env_file:
      - .env
    volumes:
      - ./otel-collector/config.yml:/etc/otelcol/config.yml
    command: ["--config=/etc/otelcol/config.yml"]
    ports:
      - "4318:4318"
  app-python:
    build: ./app
    depends_on:
      - otel-collector
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=DELTA
